-- AlterTable
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "bloodGroup" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "fatherName" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "fatherPhone" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "fatherOccupation" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "motherName" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "motherPhone" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "motherOccupation" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "parentAddress" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "emergencyContact" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "emergencyPhone" TEXT;
